spring:
  application:
    name: examplatform
  profiles:
    active: dev
  jpa:
    open-in-view: false


  management:
    endpoints:
      web:
        exposure:
          include: health, info
    endpoint:
      health:
        show-details: when-authorized
